// vue2-grand-child/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <div></div>
    <label>Post message</label>&nbsp;
    <output>{{postMessage}}</output>
    <br />
    <label>localStorage</label>&nbsp;
    <output>{{storage}}</output>
    <br />
    <label>Send Post Message to React</label>
    <input :on-change="this.sendPostMessageToParent()" v-model="inputPostMessageValue"/>
  </div>
</template>

<script>
// import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'App',
  data() {
    return {
      postMessage: '',
      storage: '',
      inputPostMessageValue: ''
    }
  },
  methods: {
    receivePostMessage (event) {
      console.log(event);
      if (event.origin === "http://localhost:3000") {
        this.postMessage = event.data;
      }
    },
    receiveLocalStorageData (event) {
      console.log(event);
    },
    sendPostMessageToParent () {
      window.parent.postMessage(this.inputPostMessageValue, "http://localhost:3000");
    }
  },
  mounted() {
    window.addEventListener('message', this.receivePostMessage);
    window.addEventListener('storage', this.receiveLocalStorageData);
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  
}
</style>

// react-typescript/src/App.tsx
import React, { ChangeEvent, useCallback, useEffect, useRef, useState } from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  const [postMessage, setPostMessage] = useState('');
  const [storageData, setStorageData] = useState('');
  const [grandChildPostMessage, setGrandChildPostMessage] = useState('');

  const iframeRef = useRef<HTMLIFrameElement>(null);

  const receivePostMessage = useCallback((event: MessageEvent) => {
    setGrandChildPostMessage(JSON.stringify(event.data));
    console.log(event);
  }, []);

  useEffect(() => {
    window.addEventListener('message', receivePostMessage);

    return () => {
      window.removeEventListener('message',receivePostMessage );
    }
  }, [receivePostMessage]);

  const sendPostMessage = (e: ChangeEvent<HTMLInputElement>) => {
    const inputValue = e.target.value;
    setPostMessage(inputValue);
    iframeRef.current?.contentWindow?.postMessage(inputValue, "http://localhost:8080");
  }

  const sendLocalStorage = (e: ChangeEvent<HTMLInputElement>) => {
    const inputValue = e.target.value;
    setStorageData(inputValue);
    window.localStorage.setItem('react-data', inputValue);
  }

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} alt="react"/>
        <label htmlFor="react-input">
          react post message
        </label>
        <input
          type="text"
          name="react-input"
          id="react-input"
          value={postMessage}
          onChange={sendPostMessage}
        />
        <label htmlFor="react-input">
          react local storage
        </label>
        <input
          type="text"
          name="react-input"
          id="react-input"
          value={storageData}
          onChange={sendLocalStorage}
        />
        <br />
        <label>Post message from grand child</label>
        <output>{grandChildPostMessage}</output>
      </header>
      <iframe
        ref={iframeRef}
        src="http://localhost:8080"
        title="live preview">
      </iframe>
    </div>
  );
}

export default App;
